import type { GambolBroker, GambolUser } from '@/types';

export const GAMBOL_BROKERS: GambolBroker[] = [
  {
    id: 'optgo',
    name: 'OPTGO Broker (Oficial)',
    logo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=64&h=64&fit=crop&auto=format',
    fallbackLogo: 'https://api.dicebear.com/7.x/identicon/svg?seed=optgo',
    status: 'online',
    latency: 3,
    payout: 95,
    serverRegion: 'São Paulo (BR-OTC1 - TradeRoom Live)',
    tradeRoomUrl: 'https://trade.optgobroker.com/traderoom',
  },
  {
    id: 'alpha',
    name: 'Broker-Alpha',
    logo: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=64&h=64&fit=crop&auto=format',
    fallbackLogo: 'https://api.dicebear.com/7.x/identicon/svg?seed=alpha',
    status: 'online',
    latency: 8,
    payout: 93,
    serverRegion: 'São Paulo (BR-SP1)',
  },
  {
    id: 'quotex',
    name: 'Quotex',
    logo: 'https://images.unsplash.com/photo-1642543492481-44e81e3914a7?w=64&h=64&fit=crop&auto=format',
    fallbackLogo: 'https://api.dicebear.com/7.x/identicon/svg?seed=quotex',
    status: 'online',
    latency: 6,
    payout: 92,
    serverRegion: 'Frankfurt (DE-FRA1)',
    tradeRoomUrl: 'https://qxbroker.com/pt/trade',
  },
  {
    id: 'blaze',
    name: 'Blaze Invest',
    logo: 'https://images.unsplash.com/photo-1622979135225-d2ba269bc1df?w=64&h=64&fit=crop&auto=format',
    fallbackLogo: 'https://api.dicebear.com/7.x/identicon/svg?seed=blaze',
    status: 'online',
    latency: 12,
    payout: 89,
    serverRegion: 'Ashburn (US-VA2)',
  },
  {
    id: 'iq',
    name: 'IQ Option',
    logo: 'https://images.unsplash.com/photo-1621416894569-0f39ed31d247?w=64&h=64&fit=crop&auto=format',
    fallbackLogo: 'https://api.dicebear.com/7.x/identicon/svg?seed=iq',
    status: 'online',
    latency: 9,
    payout: 88,
    serverRegion: 'London (UK-LON)',
  },
  {
    id: 'xoption',
    name: 'X Option',
    logo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=64&h=64&fit=crop&auto=format',
    fallbackLogo: 'https://api.dicebear.com/7.x/identicon/svg?seed=xoption',
    status: 'online',
    latency: 11,
    payout: 90,
    serverRegion: 'Dublin (IE-DUB)',
  },
  {
    id: 'globaloption',
    name: 'Global Option',
    logo: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=64&h=64&fit=crop&auto=format',
    fallbackLogo: 'https://api.dicebear.com/7.x/identicon/svg?seed=globaloption',
    status: 'online',
    latency: 14,
    payout: 87,
    serverRegion: 'Tokyo (JP-TYO)',
  },
  {
    id: 'exora',
    name: 'Exora',
    logo: 'https://images.unsplash.com/photo-1620321023374-d1a68fbc720d?w=64&h=64&fit=crop&auto=format',
    fallbackLogo: 'https://api.dicebear.com/7.x/identicon/svg?seed=exora',
    status: 'online',
    latency: 10,
    payout: 91,
    serverRegion: 'Miami (US-MIA)',
  },
  {
    id: 'polarium',
    name: 'Polarium Broker',
    logo: 'https://images.unsplash.com/photo-1634704784915-aacf363b021f?w=64&h=64&fit=crop&auto=format',
    fallbackLogo: 'https://api.dicebear.com/7.x/identicon/svg?seed=polarium',
    status: 'online',
    latency: 13,
    payout: 89,
    serverRegion: 'Singapore (SG-SIN)',
  },
  {
    id: 'exnova',
    name: 'Exnova',
    logo: 'https://images.unsplash.com/photo-1640340434855-6084b1f4901c?w=64&h=64&fit=crop&auto=format',
    fallbackLogo: 'https://api.dicebear.com/7.x/identicon/svg?seed=exnova',
    status: 'online',
    latency: 12,
    payout: 88,
    serverRegion: 'Amsterdam (NL-AMS)',
  },
  {
    id: 'avalon',
    name: 'Avalon',
    logo: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=64&h=64&fit=crop&auto=format',
    fallbackLogo: 'https://api.dicebear.com/7.x/identicon/svg?seed=avalon',
    status: 'online',
    latency: 15,
    payout: 86,
    serverRegion: 'Sydney (AU-SYD)',
  },
  {
    id: 'ebinex',
    name: 'Ebinex',
    logo: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=64&h=64&fit=crop&auto=format',
    fallbackLogo: 'https://api.dicebear.com/7.x/identicon/svg?seed=ebinex',
    status: 'online',
    latency: 14,
    payout: 90,
    serverRegion: 'Zurich (CH-ZRH)',
  },
];

export const GAMBOL_VIP_USER: GambolUser = {
  nome: 'Trader VIP Master',
  email: 'blackmoney3052@gmail.com',
  whatsapp: '+55 (11) 98765-4321',
  planName: 'Acesso Vitalício VIP Master (Desbloqueado)',
  subscriptionStartLabel: 'Ativo Permanente',
  subscriptionEndLabel: 'Acesso Vitalício (Sem Expiração)',
  subscriptionActive: true,
  lifetime: true,
  connectedServers: 12,
  balance: 14250.0,
  demoBalance: 50000.0,
};
